name: fire
channels:
  - conda-forge
dependencies:
  - python=3.10  
  - rasterio
  - numpy
  - matplotlib
  - gdal
  - scikit-image  # includes skimage
  - geopandas
  - requests
  - shapely
  - jupyter
  - ipykernel
  - opencv
